package com.kyc.customer.entity;

public enum EventType {
    CLIENT_REGISTERED,
    KYC_FORM_SUBMITTED,
    KYC_APPROVED,
    KYC_REJECTED,
    ACCOUNT_CREATED,
    ACCOUNT_STATUS_UPDATED,
    ACCOUNT_CREDITED,
    ACCOUNT_DEBITED
}
